#!/usr/bin/env bash
#
# Set up corporate CA certificate for Docker builds behind TLS-intercepting proxies (e.g. Netskope).
#
# Usage: ./docker/setup-certs.sh /path/to/corporate-ca.pem
#
# This creates:
#   .docker/certs/ca-cert.pem       - copy of the cert (gitignored)
#   docker-compose.override.yml     - build secret config (gitignored)
#
# After running this, `docker compose build` / `make build` will inject the cert
# into all containers during build. No changes needed for devs without a proxy.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

if [ $# -ne 1 ]; then
    echo "Usage: $0 /path/to/corporate-ca.pem"
    exit 1
fi

CERT_FILE="$1"

if [ ! -f "$CERT_FILE" ]; then
    echo "Error: Certificate file not found: $CERT_FILE"
    exit 1
fi

# Validate it looks like a PEM certificate
if ! grep -q "BEGIN CERTIFICATE" "$CERT_FILE"; then
    echo "Error: File does not appear to be a PEM certificate: $CERT_FILE"
    exit 1
fi

# Copy cert to gitignored location
mkdir -p "$PROJECT_ROOT/.docker/certs"
cp "$CERT_FILE" "$PROJECT_ROOT/.docker/certs/ca-cert.pem"

# Generate docker-compose.override.yml
cat > "$PROJECT_ROOT/docker-compose.override.yml" <<'EOF'
# Auto-generated by docker/setup-certs.sh — DO NOT COMMIT
# Injects corporate CA cert into Docker builds for TLS-intercepting proxies
services:
  api:
    build:
      secrets:
        - ca_cert
  pocketbase:
    build:
      secrets:
        - ca_cert
  frontend:
    build:
      secrets:
        - ca_cert

secrets:
  ca_cert:
    file: .docker/certs/ca-cert.pem
EOF

echo ""
echo "Corporate CA cert configured for Docker builds."
echo ""
echo "  Cert:     .docker/certs/ca-cert.pem"
echo "  Override:  docker-compose.override.yml"
echo ""
echo "Both files are gitignored. Run 'make build' or 'docker compose build' to build with cert injection."
