# image source here: https://github.com/devcontainers/images/tree/main/src/universal
FROM mcr.microsoft.com/devcontainers/universal:linux

# Copy noop.txt to prevent COPY instruction from failing
COPY .devcontainer/standard/noop.txt /tmp/noop.txt
