#!/bin/bash

### Script that runs once after project setup (postCreateCommand)
### Handles SSH keys, Claude Code config, and .env generation

echo "Running Post Create Hook Script: post_create_hook.sh"

# make aliases expand and work in the script
shopt -s expand_aliases

WORKSPACE="/workspaces/gvca_sac"

# --- SSH Private Key Setup ---
echo "Setting up SSH private key..."
if [ -n "$SSH_PRIVATE_KEY" ]; then
    echo "SSH_PRIVATE_KEY found. Setting up SSH authentication..."
    mkdir -p ~/.ssh
    chmod 700 ~/.ssh
    echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
    chmod 600 ~/.ssh/id_ed25519
    eval "$(ssh-agent -s)"
    ssh-add ~/.ssh/id_ed25519
    echo "SSH private key configured successfully"
else
    echo "SSH_PRIVATE_KEY not found. SSH key setup skipped."
    echo "To setup SSH key, add SSH_PRIVATE_KEY to your Codespace secrets."
fi

# --- Claude Code GitHub MCP Server Setup ---
echo "Setting up GitHub MCP server for Claude Code..."
if command -v claude >/dev/null 2>&1; then
    mkdir -p ~/.config/claude

    if [[ -v GITHUB_TOKEN ]]; then
        echo "GITHUB_TOKEN found. Configuring GitHub MCP server..."
        if ! claude mcp list 2>/dev/null | grep -q "github:"; then
            claude mcp add-json github '{
              "type": "http",
              "url": "https://api.githubcopilot.com/mcp/",
              "headers": {
                "Authorization": "Bearer '"${GITHUB_TOKEN}"'"
              }
            }' 2>/dev/null
        else
            echo "GitHub MCP server already configured."
        fi

        if claude mcp list | grep -q "github"; then
            echo "GitHub MCP server (remote) configured successfully."
        else
            echo "GitHub MCP server configuration may have failed. Please verify with: claude mcp list"
        fi
    elif [[ -v CODESPACES ]] && gh auth status >/dev/null 2>&1; then
        echo "Attempting to use GitHub token from Codespaces gh CLI authentication..."
        GITHUB_TOKEN=$(gh auth token 2>/dev/null)
        if [[ -n "${GITHUB_TOKEN}" ]]; then
            if ! claude mcp list 2>/dev/null | grep -q "github:"; then
                claude mcp add-json github '{
                  "type": "http",
                  "url": "https://api.githubcopilot.com/mcp/",
                  "headers": {
                    "Authorization": "Bearer '"${GITHUB_TOKEN}"'"
                  }
                }' 2>/dev/null
            else
                echo "GitHub MCP server already configured."
            fi
            if claude mcp list | grep -q "github"; then
                echo "GitHub MCP server (remote) configured successfully using Codespaces token."
            fi
        else
            echo "Could not retrieve token from gh CLI."
        fi
    else
        echo "WARNING: GITHUB_TOKEN not found. GitHub MCP server requires authentication."
        echo "To complete GitHub MCP server setup:"
        echo "1. Ensure GITHUB_TOKEN is added to your Codespace secrets, or"
        echo "2. Run: export GITHUB_TOKEN=your_pat_token"
    fi
else
    echo "Claude Code not found - skipping GitHub MCP server installation."
fi

# --- Generate .env file ---
echo "Generating .env file..."
cat > "${WORKSPACE}/.env" << ENVEOF
# Auto-generated by post_create_hook.sh for Codespaces
# PocketBase
POCKETBASE_URL=http://localhost:8090
VITE_POCKETBASE_URL=http://localhost:8090

# Paths (workspace-relative for Codespaces)
DATA_DIR=${WORKSPACE}/data
ARTIFACTS_DIR=${WORKSPACE}/artifacts

# Vite proxy target (localhost instead of Docker service name)
VITE_PROXY_TARGET=http://localhost:8000

# API keys (from Codespace secrets)
OPENAI_API_KEY=${OPENAI_API_KEY:-}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
ENVEOF

echo ".env file generated at ${WORKSPACE}/.env"

echo "Post Create Hook Script Complete"
